[build]
  # no static build; just publish /public
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["data/**"]    # ship suppliers-codes.xlsx & categories-descriptions.xlsx

# (Optional but helpful — auto-install function deps)
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
