[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  # ship the two mapping Excels with the functions bundle
  included_files = [
    "data/suppliers-codes.xlsx",
    "data/categories-descriptions.xlsx"
  ]
